services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    build:
      context: .
      dockerfile: Dockerfile.opensearch
    env_file:
      - env.test
    environment:
      - cluster.name=opensearch # Name the cluster
      - node.name=opensearch-node # Name the node that will run in this container
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - discovery.type=single-node
      - OPENSEARCH_HOST=https://opensearch:9200
      - OPENSEARCH_USER=admin
      - OPENSEARCH_PASSWORD=WD71969!Bill
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=WD71969!Bill
      - OPENSEARCH_USERNAME=admin
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    tmpfs:
      - /usr/share/opensearch/nodes # Use tmpfs so no data is persisted between runs
    ports:
      - 9200:9200 # REST API
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network


networks:
  opensearch-net:
